Add VszLimit property (#192)
When VszLimit prop is empty (default), dovecot will use its default
value for 'default_vsz_limit' option.
Otherwise, VszLimit can have an integer value expressed in 'M' unit.

This implemention preserve the current behavior and should also
avoid conflicts with existing template customs.

The VszLimit prop should be changed only when users have hundreds of
thousands mails inside the INBOX.
The evidence is an error like:

 Error: mmap() failed with file  [..]/Maildir/dovecot.index.cache: Cannot allocate memory

NethServer/dev#6118

Co-Authored-By: Davide Principi <davide.principi@nethesis.it>